name: Nestjs CI

on:
  push:
    branches: ["develop"]
    paths:
      - 'backend/**'
  pull_request:
    branches: ["develop"]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10.32.1

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'pnpm'
          cache-dependency-path: './backend/'

      - name: "Install dependencies"
        run: pnpm install

      - name: "Prisma Generate"
        run: pnpm prisma generate

      - name: "Build"
        run: pnpm run build
