name: CI

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'frontend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # name of the job
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.32.1

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'pnpm'
          cache-dependency-path: './frontend/'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
